### ISSUE TITLE
UIView+Layout additions from other projects

### ISSUE THREAD

**Issue by jamaine-ustwo** [ustwo/autolayout-helper-swift#4]
Hey @madhikarma over the past couple weeks @aamctustwo has added some cool helper methods to 'UIView+Layout' , may be some stuff you find useful or interesting to you!

Aaron added some methods to search and retrieve constraint objects via an string identifier so you can change individual layout  constraints having called 'fillSuperview'

Jam

**Comment by madhikarma** [comment]
Interesting, the original idea was to support creating the constraints easily and focused less on retrieval (leaving that responsibility to the callee). 

I think its worth a pull request though and see what others think!

**Comment by madhikarma** [comment]
@aamctustwo feel free to branch and submit a PR sometime if you want too 

If you don't then its fine if you guys have modified the library directly (although my OCD tells me otherwise and prefers non core additions to be project specific extensions)

Hopefully we will have https://github.com/ustwo/autolayout-helper-swift/issues/2 and https://github.com/ustwo/autolayout-helper-swift/issues/3 resolved if you guys want to integrate as a framework via submodule or pod instead

**Comment by madhikarma** [comment]
I think other project contributions could belong to those projects (e.g. as a fork) and contributed back but I'm not sure the retrieval one mentioned above is what I had in mind for this library, I was thinking more about the layout rules themselves. I'll add something about how to contribute to the README file and close this one for now if it's ok
